apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "controller.name" . }}
  labels:
      {{- include "controller.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "controller.name" . }}
      {{- include "controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "controller.name" . }}
        {{- include "controller.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "controller.name" . }}
      containers:
        - name: {{ include "controller.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["java", "-jar", "/app.jar", "--spring.config.location=/tmp/controller-config/application.yml"]
          ports:
            - name: http
              containerPort: {{ .Values.server.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /tmp/controller-config
              name: controller-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: controller-config
          configMap:
            name: {{ include "controller.name" . }}
            defaultMode: 0777
            items:
              - key: application.yml
                path: application.yml
