apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "controller.name" . }}
  labels:
      {{- include "controller.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "pods/exec"]
    verbs: ["get", "list", "post", "patch", "update"]