apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "controller.name" . }}
  labels:
      {{- include "controller.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "controller.name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "controller.name" . }}